version: '3.1'

services:
  mongodb:
    image: mongo
    restart: on-failure:5
    ports:
      - 27027:27017
    environment:
      MONGO_INITDB_DATABASE: project_api
    volumes:
      - dbvolume:/data/db

volumes:
  dbvolume:
